### ISSUE TITLE
Spring Security error on application run

### ISSUE THREAD

**Issue by dominik-myszkowski** [hantsy/angular-spring-reactive-sample#2]
There is @EnableWebFluxSecurity annotation missing on SecurityConfig class.
It produces an error:
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method springWebFilterChain in org.knight.posts.SecurityConfig required a bean of type 'org.springframework.security.config.web.server.ServerHttpSecurity' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.security.config.web.server.ServerHttpSecurity' in your configuration.

**Comment by hantsy** [comment]
1. `ServerHttpSecurity` is provide in *reactive* web.
2. `@EnableWebFluxSecurity` is not required in Spring Boot.

Just verified, everything worked well.
