### ISSUE TITLE
Had to set several PostControllerTests to Ignore to get this to build.

### ISSUE THREAD

**Issue by jaschenk** [hantsy/angular-spring-reactive-sample#3]
The following tests had to be set to @Ignore to get around issues:

PostControllerTest.createCommentOfPost_shouldBeOk

PostControllerTest.getAllPosts_shouldBeOk

PostControllerTest.getAllPostsByKeyword_shouldBeOk

Not sure if these need to be run against a clean MongoDB Collection or not.

Just make folks aware.

**Comment by hantsy** [comment]
@jaschenk Some changes of the newest Spring Boot broke the tests, I have updated tests to make most of the tests works(two are left for finding solutions), thanks for reporting this.
