### ISSUE TITLE
This isn't reactive

### ISSUE THREAD

**Issue by dalu** [hantsy/angular-spring-reactive-sample#4]
https://github.com/hantsy/angular-spring-reactive-sample/blob/master/client/src/app/post/shared/post.service.ts

Where is the reactive part? Do you know what reactive means?
It means you receive a stream of updates to your subscriptions.
So when ever someone enters new data, that data is propagated to the client

**Comment by hantsy** [comment]
@dalu Angular `HttpClient` is based on RXJS which implements ReactiveStream spec, what is  Reactive in your mind. Please your idea, or contribute your codes to this sample project.

**Comment by dalu** [comment]
It's not reactive, it's a one way roundtrip.
When you call subscribe you do exactly 1 xmlhttprequest.
Reactive means you receive a stream of data.

My idea and implementation was on the angular side to connect to a websocket that sends out notifications when database stuff happens.
But I'm not using Java, but Go. However I was interested in how that works with Java and Angular.

So there is a blogpost which uses EventSource, that has less browser support and isn't even properly supported by zone.js  that Angular uses.
https://grokonez.com/reactive-programming/angular-4-spring-webflux-spring-data-reactive-mongodb-example-full-reactive-angular-4-http-client-spring-boot-restapi-server
When you look at the customer.service.ts you see an observer is being created and an EventSource is being polled. And every new data the subscribers are notified via `observer.next(new-data)`

This is more akin to being reactive, the problem is it doesn't work. The EventSource  either times out or when I set it to 24h it only receives data randomly. I don't know what the deal there is. And if you want to use EventSource on Edge you need a polyfill.

My solution is, like I wrote, have a websocket that provides the client(angular) with notifications of new data e.g.

```json
{
"id":"some id, string, uuid or objectid",
"collection": "posts",
"action": "update|insert|delete"
}
```

then you can subscribe in the client and `pipe(filter(notification => notification.action === 'update' && notification.collection === 'posts')).subscribe(() => this.reloadData())`

**Comment by dalu** [comment]
Btw I stumbled upon your repo  because I was searching for how to do it with Spring Boot, so I can't tell you how to do that on the Spring Boot side. As for the websocket client part,

```ts
import {Injectable} from '@angular/core';
import {Observable, Observer, Subject} from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class WebSocketService {
  private subject: Subject<MessageEvent>;

  constructor() {
  }

  public connect(url: string): Subject<MessageEvent> {
    if (!this.subject) {
      this.subject = this.create(url);
    }
    return this.subject;
  }

  private create(url: string): Subject<MessageEvent> {
    const ws = new WebSocket(url);
    const observable = Observable.create(
      (obs: Observer<MessageEvent>) => {
        ws.onmessage = obs.next.bind(obs);
        ws.onerror = obs.error.bind(obs);
        ws.onclose = obs.complete.bind(obs);
        return ws.close.bind(ws);
      }
    );
    const observer = {
      next: (data: Object) => {
        if (ws.readyState === WebSocket.OPEN) {
          ws.send(JSON.stringify(data));
        }
      }
    };
    return Subject.create(observer, observable);
  }
}
```

**Comment by dalu** [comment]
No one says anything either way but this repo is named "angular-spring-reactive-sample" so one can expect a truly reactive frontend with the currently reactive backend you do have. But your frontend isn't reactive.

Real time or Reactive is the same, it's arguing over potajto potato. Everything else is plain old REST.

Most of the time that may be true, however, I repeat myself, your frontend isn't whatever you want to call it, real-time or reactive.

And again angular's HttpClient's subscribe does 1 request.

This discussion is pointless. This isn't a reactive example.

**Comment by dalu** [comment]
You can close this but the fact of the matter remains, this repo isn't reactive, what you claim it to be
