### ISSUE TITLE
Upload file with server side progress bar

### ISSUE THREAD

**Issue by jaypatil** [hantsy/angular-spring-reactive-sample#6]
Hi Hantsy,

This example is very helpful, I have checked your Spring flux file upload example as well. But I would like to request you to add one more feature Could you please add Upload file feature with server side progress bar in a spring web flux way. It would be very helpful. Thanks in advance.

Regards,
Jay Kumar Patil

**Comment by hantsy** [comment]
You can track the progress in your client, http://christopher5106.github.io/web/2015/12/13/HTML5-file-image-upload-and-resizing-javascript-with-progress-bar.html
