### ISSUE TITLE
Client login returns 401 in browser but working fine via postman - Unauthorized error. Message - Full authentication is required to access this resource

### ISSUE THREAD

**Issue by samu7** [hantsy/angular-spring-reactive-sample#7]
I implemented the exact same in client with JWT authentication. The Server authentication works when requested via postman but unable to get the same at client side.

```
attempAuth(credentials: Credentials): Observable<any> {
    console.log('attempAuth ::');
    return this.http.post<any>(`${apiUrl}/login`, {"username":credentials.username,"password":credentials.password},)
      .pipe(
      tap(data => {
        console.log('do::');
        console.log(data);
        this.store.setState({
          user: data, authenticated: Boolean(data)
        });
      })
      );
  }
```

I'm stuck on this, Getting error as **Unauthorized error. Message - Full authentication is required to access this resource**

Any response would be of great help!

**Comment by hantsy** [comment]
@samu7 This sample is using Spring Session for security. The progress is similar with JWT.  If you are using JWT, you could have to change the header inteceptor in the to make it work.
https://github.com/hantsy/angular-spring-reactive-sample/blob/master/client/src/app/core/token-inteceptor.ts

**Comment by hantsy** [comment]
@samu7 Can you confirm if this problem is resolved?
