### ISSUE TITLE
why do u use Session

### ISSUE THREAD

**Issue by HelloTo4x** [hantsy/angular-spring-reactive-sample#79]
Hi, why do you use Session instead of JWT or Cookie or other authentications... Can u explain me why u choose it, thank u so much

**Comment by hantsy** [comment]
It is an alternative solution to replace JWT, and provides cookies and
headers support in Client, it is easy to be integrated in all cases that
JWT can do.

Of course, if you like JWT like stateless token, check out
https://github.com/hantsy/spring-reactive-jwt-sample
---

Regards,

*Hantsy Bai*

Self-employed consultant, fullstack developer, agile coach,
freelancer/remote worker

GitHub: https://github.com/hantsy

Twitter: ***@***.***
Medium: ***@***.***

**Comment by hantsy** [comment]
@HelloTo4x What is I used is Spring Session(can be a backend of Mongo, Redis, etc.), not generic HttpSession.

**Comment by HelloTo4x** [comment]
thank u so much
